spring:
  application:
    name: User-app
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    password: 12345678
    username: postgres

jks:
  alias: mykey
  name: mykeystore.jks
  key: 12345678
  private-key: 12345678

app:
  cfg:
    authorization:
      enabled: true