spring:
  application:
    name: User-app
  datasource:
    url: jdbc:postgresql://${DATASOURCE_URI}:${DATASOURCE_PORT}/${DATASOURCE_DB}
    password: ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USERNAME}

jks:
  alias: mykey
  name: mykeystore.jks
  key: ${KEYSTORE_KEY}
  private-key: ${PRIVATE_KEY}

app:
  cfg:
    authorization:
      enabled: true
    kafka:
      enabled: true

myapp:
  bootstrap-servers: ${KAFKA_URI}
  topics:
    name: someTopic