spring:
  application:
    name: User-app
  datasource:
    url: jdbc:postgresql://${DATASOURCE_URI}:${DATASOURCE_PORT}/${DATASOURCE_DB}
    password: ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USERNAME}

jks:
  alias: mykey
  name: mykeystore.jks
  key: ${KEYSTORE_KEY}
  private-key: ${PRIVATE_KEY}

app:
  cfg:
    authorization:
      enabled: true
    kafka:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka/
myapp:
  bootstrap-servers: ${KAFKA_URI}
  topics:
    name: someTopic

logging:
  level:
    org:
      springframework:
        web: DEBUG
      example:
        user: DEBUG